
spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: jdbc:h2:mem:lpqtestdb
    driver-class-name: org.h2.Driver
    username: lpq
    password:

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    st.tiy: DEBUG
    org.hibernate: INFO
    org.apache: INFO

